### PR TITLE
fix: Correctly handle null values in JSON variations.

### LINKED ISSUE #568: Issue running with the example code from the node redis integration.
**Describe the bug**
The example provided in the README.md is not working

**To reproduce**
```ts
import { init } from '@launchdarkly/node-server-sdk';
import { RedisFeatureStore } from '@launchdarkly/node-server-sdk-redis';

(async function main() {
  const client = init(process.env.LD_KEY!, {
    featureStore: RedisFeatureStore(),
  });
  await client.waitForInitialization({ timeout: 5 });
})();
```

**Expected behavior**
Not to throw errors

**Logs**
```
~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/serialization.js:42
    if (value.generated_includedSet) {
              ^

TypeError: Cannot read properties of undefined (reading 'generated_includedSet')
    at Array.replacer (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/serialization.js:42:15)
    at JSON.stringify (<anonymous>)
    at serializeFlag (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/serialization.js:248:17)
    at Object.serialize (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/persistentStoreKinds.js:45:70)
    at visit (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:34:24)
    at topologicalSort (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:40:9)
    at ~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:59:40
    at Array.forEach (<anonymous>)
    at sortDataSet (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:57:26)
    at ~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/PersistentDataStoreWrapper.js:107:54
```
**SDK version**
- @launchdarkly/node-server-sdk: 9.5.3
- @launchdarkly/node-server-sdk-redis: 4.1.20

**Language version, developer tools**
Node: 20.17.0

**OS/platform**
Mac OS Sonoma 14.6.1 (23G93)

### PR DESCRIPTION
**Pull request by kinyoklion**
During the typescript implementation null values were removed during JSON de-serialization. This was over-zealous as variations can be JSON which contains null values.

This retains null value removal for everything aside from variations.

The reason this was originally done is to simplify all code which interacts with the data model (It only needs to check undefined versus null/undefined.). It also simplifies the ability to produce a compact representation that omits any null fields.

In the future we may want to consider removing this behavior.

Fixes #568

### CODE REVIEW

File: packages/shared/sdk-server/src/store/serialization.ts [hunk 1]
```diff
@@ -35,6 +22,63 @@ export interface AllData {
...
+    skip: boolean;
+  }[] = [];
+
+  if (target === null || target === undefined) {
+    return;
+  }
+
+  stack.push(
+    ...Object.entries(target).map(([key, value]) => ({
+      skip: excludeKeys?.includes(key) ?? false,
```
Comment (tanderson-ld) [inline packages/shared/sdk-server/src/store/serialization.ts:50]: Consider filter and eliminate skip.

**Review by tanderson-ld — APPROVED** [review]
