### PR TITLE
fix: Stream retry failure due to previous open connection.

### LINKED ISSUE #405: Streaming not working on react-native android even with Flipper removed
**Describe the bug**

Even with Flipper completely removed from our `react-native` project (as bullet point 4 describes here: <https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native#known-android-identify-issue>), streaming still doesn't seem to be working properly for Android. The app doesn't hang on `identify` and initial flags are retrieved so thats good. But any changes to the LD flags through our dashboard are not being reflected live in the Android app as they should. The streaming is working as expected on iOS.

**To reproduce**

I have tried using the exact code from the quickstart section: <https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native#quickstart> and the streaming changes are reflected live on iOS but not on android.

I think this issue should be quickly apparent, but please let me know if you need any more reproduction details!

**Expected behavior**

Updating the flags on the LD dashboard should immediately be reflected in the Android app like they are on iOS

**Logs**

On Android on app startup:

```
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Will retry stream connection in 915 milliseconds
```

For comparison on iOS on app startup:
Note: there is no line about retrying the streaming connection in x milliseconds

```
info: [LaunchDarkly] Opened LaunchDarkly stream connection
```

**SDK version**

`"@launchdarkly/react-native-client-sdk": "^10.0.3"`

**Language version, developer tools**

Not expo, just base `"react-native": "0.72.12"`

**OS/platform**

Tested on Pixel 7 Emulator and Physical Device
Android 14

### PR DESCRIPTION
**Pull request by yusinto**
This should fix #405 or at least provide more logging to debug the issue further if it persists.

### CODE REVIEW

File: packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ const defaultOptions: EventSourceOptions = {
   timeout: 0,
   withCredentials: false,
   retryAndHandleError: undefined,
-  initialRetryDelayMillis: 1000,
+  initialRetryDelayMillis: 5000,
```
Comment (yusinto) [inline packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts:20]: Increasing this on a mobile device seems like a good idea so as to not drain power.

File: packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts [hunk 2]
```diff
@@ -93,6 +93,7 @@ export default class EventSource<E extends string = never> {
     this.logger?.debug(`[EventSource] Will open new connection in ${delay} ms.`);
     this.dispatch('retry', { type: 'retry', delayMillis: delay });
     this.pollTimer = setTimeout(() => {
+      this.close();
```
Comment (yusinto) [inline packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts:96]: `react-native` has its own implementation of `XMLHttpRequest` which throws an error if a previous connection is still `open` and you try to re-open it. Here we are closing the connection first to solve that error.

File: packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts [hunk 3]
```diff
@@ -315,6 +316,7 @@ export default class EventSource<E extends string = never> {
         this.onclose();
         break;
       case 'error':
+        this.logger?.debug(`[EventSource][dispatch][ERROR]: ${JSON.stringify(data)}`);
```
Comment (yusinto) [inline packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts:319]: This is much needed for debugging.

File: packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts (hunk 1 above)
Comment (kinyoklion) [reply packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts:20]: I would rather change this independently, unless it contributes to the fix. Because the initial retry is 1 second, when streaming, among the SDKs.

**Review by kinyoklion — APPROVED** [review]

**Review by kinyoklion — CHANGES_REQUESTED** [review]
Tests are failing.

**Review by kinyoklion — APPROVED** [review]
